choco install atom.install -y
choco install audacity -y
choco install autohotkey -y
choco install autohotkey.install -y
choco install chocolatey -y
choco install chocolatey-compatibility.extension -y
choco install chocolatey-core.extension -y
choco install chocolatey-dotnetfx.extension -y
choco install chocolatey-windowsupdate.extension -y
choco install discord -y
choco install discord.install -y
choco install dotnet-6.0-desktopruntime -y
choco install dotnet-7.0-desktopruntime -y
choco install dotnet-desktopruntime -y
choco install DotNet4.5.2 -y
choco install dotnetfx -y
choco install Everything -y
choco install figma -y
choco install Firefox -y
choco install flow-launcher -y
choco install gh -y
choco install git -y
choco install git.install -y
choco install GoogleChrome -y
choco install KB2919355 -y
choco install KB2919442 -y
choco install KB2999226 -y
choco install KB3033929 -y
choco install KB3035131 -y
choco install KB3063858 -y
choco install mobaxterm -y
choco install nanazip.portable -y
choco install nmap -y
choco install nodejs -y
choco install nodejs.install -y
choco install notepadplusplus -y
choco install notepadplusplus.install -y
choco install obsidian -y
choco install powerautomatedesktop -y
choco install powertoys -y
choco install python3 -y
choco install rpi-imager -y
choco install rsync -y
choco install rufus -y
choco install sharex -y
choco install slack -y
choco install sublimetext3 -y
choco install ueli -y
choco install vagrant -y
choco install vcredist140 -y
choco install vcredist2015 -y
choco install virtualbox -y
choco install vscode -y
choco install vscode.install -y
choco install wincompose -y
choco install wincompose.install -y
